# Generated by Django 3.2.7 on 2021-09-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
